# Generated by Django 4.0.1 on 2022-01-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_husband_account_husband_or_wife_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='husband_or_wife',
            new_name='spouse',
        ),
    ]
