# Generated by Django 4.0.1 on 2022-01-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('salary', 'Salary'), ('unexpected', 'Unexpected'), ('work', 'Work'), ('small_business', 'Small business'), ('other', 'Other')], max_length=64),
        ),
    ]
