# Generated by Django 4.0.1 on 2022-01-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_expense_amount_alter_income_amount_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('unexpected', 'Unexpected'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('supper', 'Supper'), ('clothing', 'Clothing'), ('clothing', 'Clothing'), ('parents', 'Parents'), ('debt', 'Debt'), ('phone', 'Phone'), ('charity', 'Charity')], max_length=64),
        ),
    ]
