# Generated by Django 4.0.1 on 2022-01-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_expense_type_alter_income_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
