# Generated by Django 4.0.1 on 2022-01-27 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_expense_payed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payed_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
